[package]
name = "hodeauxledger-services"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
ed25519-dalek = "2.2.0"
hodeauxledger-core = { path = "../hodeauxledger-core" }
hodeauxledger-io = { path = "../hodeauxledger-io" }
serde_json = "1.0.143"
